# Default values for conan-ci.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

host: conan-ci

user: conanci

conan-server:
  host_name: conan.conan-ci
  user: agent
  password: demo

mysql:
  imageTag: 8.0.21
  mysqlRootPassword: secret
  mysqlDatabase: conan-ci

phpmyadmin:
  db:
    chartName: mysql

services:
  - name: public
    public: true
  - name: scheduler
  - name: crawler
    public: true
  - name: linux-agent
    docker: true
    image: agent
    replicas: 1

windows:
  - name: one
    image: agent

sshKey: |
  -----BEGIN OPENSSH PRIVATE KEY-----
  b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
  QyNTUxOQAAACD+hNcWoKOxi8XK4zeHuY04rCipe3NjVnZ7s0XNCs3bFAAAAKBgr5OBYK+T
  gQAAAAtzc2gtZWQyNTUxOQAAACD+hNcWoKOxi8XK4zeHuY04rCipe3NjVnZ7s0XNCs3bFA
  AAAECKBWevc6xFXBWX742soCr1zfdgE4ZXUE7Q4w9TvLnRDf6E1xago7GLxcrjN4e5jTis
  KKl7c2NWdnuzRc0KzdsUAAAAF21hdHpAbWF0ei1UaGlua1BhZC1UNTMwAQIDBAUG
  -----END OPENSSH PRIVATE KEY-----
