# Default values for conan-ci.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

host: conan-ci

user: conanci

conan-server:
  host_name: conan.conan-ci
  user: agent
  password: demo
  # persistence:
  #   existingClaim: conan-server


mysql:
  imageTag: 8.0.21
  mysqlRootPassword: secret
  mysqlDatabase: conan-ci
  # persistence:
  #   existingClaim: mysql

phpmyadmin:
  db:
    chartName: mysql

services:
  - name: public
    pingUrl: /api/v1/ping
  - name: scheduler
  - name: crawler
  - name: frontend
  - name: linux-agent
    docker: true
    image: agent
    replicas: 1

windows:
  image: localhost:32000/windows1909:local
  agents:
    - name: one
      image: agent
