# helm repo add center https://repo.chartcenter.io
# helm repo update

artifactory:
  ingress:
    ## If true, Artifactory Ingress will be created
    ##
    enabled: true

    ## Artifactory Ingress hostnames
    ## Must be provided if Ingress is enabled
    ##
    hosts:
      - artifactory.kubernetes

