{{- range .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "conan-ci.fullname" $ }}-{{ .name }}
  labels:
    app: {{ template "conan-ci.fullname" $ }}-{{ .name }}
spec:
  replicas: {{ .replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ template "conan-ci.fullname" $ }}-{{ .name }}
  template:
    metadata:
      labels:
        app: {{ template "conan-ci.fullname" $ }}-{{ .name }}
    spec:
      containers:
      - name:  {{ .name }}
{{- if .image }}
        image: {{ .image }}:local
{{- else }}
        image: {{ .name }}:local
{{- end }}
        imagePullPolicy: Never
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 300
        volumeMounts:
        - name: config-map
          mountPath: /config-map
{{- if .ssh }}
        - name: root
          mountPath: /root
{{- end }}
        env:
        - name: MYSQL_URL
          value: {{ $.Release.Name }}-mysql
        - name: MYSQL_ROOT_PASSWORD
          value: {{ $.Values.mysql.mysqlRootPassword }}
        - name: CONANCI_AGENT_OS
          value: Linux
        - name: CONANCI_CRAWLER_URL
          value: {{ template "conan-ci.fullname" $ }}-crawler
        - name: CONANCI_SCHEDULER_URL
          value: {{ template "conan-ci.fullname" $ }}-scheduler
        - name: CONANCI_LINUXAGENT_URL
          value: {{ template "conan-ci.fullname" $ }}-linux-agent
        - name: CONANCI_WINDOWSAGENT_URL
          value: {{ template "conan-ci.fullname" $ }}-windows-agent
        - name: CONAN_SERVER_URL
          value: {{ template "conan-ci.conan-server-url" $ }}
        - name: CONAN_SERVER_USER
          value: {{ index $.Values "conan-server" "user" }}
        - name: CONAN_SERVER_PASSWORD
          value: {{ index $.Values "conan-server" "password" }}
        - name: CONANCI_USER
          value: {{ $.Values.user }}
{{- if .docker }}
        - name: DOCKER_HOST
          value: 127.0.0.1:2375
        - name: SSH_KEY
          value: {{ $.Values.sshKey }}
{{- end }}
{{- if .docker }}
      - name: docker
        image: docker:19.03.12-dind
        command: ["dockerd", "-H", "tcp://"]
        securityContext:
          privileged: true
{{- end }}
{{- if .ssh }}
      initContainers:
      - name: {{ $.Chart.Name }}-setup
        image: busybox:1.28
        env:
        - name: SSH_KEY
          value: {{ $.Values.sshKey }}
        command: ["/bin/sh"]
        args: ["-c", "mkdir -p ~/.ssh;cp /config-map/known_hosts ~/.ssh;cp /config-map/\"$SSH_KEY\" ~/.ssh; chmod 600 ~/.ssh/\"$SSH_KEY\""]
        volumeMounts:
        - name: config-map
          mountPath: /config-map
        - name: root
          mountPath: /root
{{- end}}
      volumes:
        - name: config-map
          configMap:
            name: {{ include "conan-ci.fullname" $ }}
{{- if .ssh }}
        - name: root
          emptyDir: {}
{{- end }}
---
{{- end }}
{{- range .Values.windows }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "conan-ci.fullname" $ }}-windows-agent-{{ .name }}
  labels:
    app: {{ template "conan-ci.fullname" $ }}-windows-agent
spec:
  replicas: {{ .replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ template "conan-ci.fullname" $ }}-windows-agent
      deployment: {{ template "conan-ci.fullname" $ }}-windows-agent-{{ .name }}
  template:
    metadata:
      labels:
        app: {{ template "conan-ci.fullname" $ }}-windows-agent
        deployment: {{ template "conan-ci.fullname" $ }}-windows-agent-{{ .name }}
    spec:
      containers:
      - name:  windows-agent
{{- if .image }}
        image: {{ .image }}:local
{{- else }}
        image: {{ .name }}:local
{{- end }}
        imagePullPolicy: Never
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 300
        volumeMounts:
        - name: config-map
          mountPath: /config-map
        env:
        - name: MYSQL_URL
          value: {{ $.Release.Name }}-mysql
        - name: MYSQL_ROOT_PASSWORD
          value: {{ $.Values.mysql.mysqlRootPassword }}
        - name: CONANCI_AGENT_OS
          value: Windows
        - name: CONANCI_CRAWLER_URL
          value: {{ template "conan-ci.fullname" $ }}-crawler
        - name: CONANCI_SCHEDULER_URL
          value: {{ template "conan-ci.fullname" $ }}-scheduler
        - name: CONANCI_LINUXAGENT_URL
          value: {{ template "conan-ci.fullname" $ }}-linux-agent
        - name: CONANCI_WINDOWSAGENT_URL
          value: {{ template "conan-ci.fullname" $ }}-windows-agent
        - name: CONAN_SERVER_URL
          value: {{ template "conan-ci.conan-server-url" $ }}
        - name: CONAN_SERVER_USER
          value: {{ index $.Values "conan-server" "user" }}
        - name: CONAN_SERVER_PASSWORD
          value: {{ index $.Values "conan-server" "password" }}
        - name: CONANCI_USER
          value: {{ $.Values.user }}
        - name: DOCKER_HOST
          value: {{ template "conan-ci.fullname" $ }}-windows-docker-{{ .name }}:2375
        - name: SSH_KEY
          value: {{ $.Values.sshKey }}
      volumes:
        - name: config-map
          configMap:
            name: {{ include "conan-ci.fullname" $ }}
---
{{- end }}
