apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "conan-ci.fullname" $ }}-ingress-frontend
  annotations:
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: {{ template "conan-ci.fullname" $ }}-frontend
          servicePort: 8080
      - path: /api/v1
        pathType: Prefix
        backend:
          serviceName: {{ template "conan-ci.fullname" $ }}-public
          servicePort: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "conan-ci.fullname" $ }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /conan(/|$)(.*)
        pathType: Prefix
        backend:
          serviceName: {{ .Release.Name }}-conan-server
          servicePort: 9300
  - http:
      paths:
      - path: /phpmyadmin(/|$)(.*)
        pathType: Prefix
        backend:
          serviceName: {{ .Release.Name }}-phpmyadmin
          servicePort: 80
