apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "conan-ci.fullname" $ }}-ingress-frontend
  annotations:
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: {{ template "conan-ci.fullname" $ }}-frontend
          servicePort: 8080
      - path: /api/v1
        pathType: Prefix
        backend:
          serviceName: {{ template "conan-ci.fullname" $ }}-public
          servicePort: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "conan-ci.fullname" $ }}-ingress-phpmyadmin
  annotations:
    traefik.ingress.kubernetes.io/request-modifier: "ReplacePathRegex: ^/phpmyadmin/(.*) /$1"
spec:
  rules:
  - http:
      paths:
      - path: /phpmyadmin
        pathType: Prefix
        backend:
          serviceName: {{ .Release.Name }}-phpmyadmin
          servicePort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "conan-ci.fullname" $ }}-ingress-conan
  annotations:
    traefik.ingress.kubernetes.io/request-modifier: "ReplacePathRegex: ^/conan/(.*) /$1"
spec:
  rules:
  - http:
      paths:
      - path: /conan
        pathType: Prefix
        backend:
          serviceName: {{ .Release.Name }}-conan-server
          servicePort: 9300
