apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: http-ingress
spec:
  rules:
  - host: conan.{{ .Values.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "conan-ci.fullname" . }}-conan-server
          servicePort: 9300
  - host: public.{{ .Values.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "conan-ci.fullname" . }}-public
          servicePort: 8080
  - host: crawler.{{ .Values.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "conan-ci.fullname" . }}-crawler
          servicePort: 8080
  - host: phpmyadmin.{{ .Values.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-phpmyadmin
          servicePort: 80
