{{- range .Values.services }}
kind: Service
apiVersion: v1
metadata:
  name: {{ template "conan-ci.fullname" $ }}-{{ .name }}
spec:
  selector:
    app: {{ .name }}
  ports:
    - port: 8080
---
{{- end }}
kind: Service
apiVersion: v1
metadata:
  name: {{ template "conan-ci.fullname" . }}-conan-server
spec:
  selector:
    app: conan-server
  ports:
    - port: 9300