# Default values for conan-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

host_name: localhost
user: agent
password: demo
tag: 1.28.1
persistence:
  size: 100M