- hosts: all
  vars:
      kubevirt_version: v0.38.1
  tasks:
  - name: Add packer repository signing key
    apt_key:
      url: https://apt.releases.hashicorp.com/gpg
    become: yes
  - name: add packer apt repository
    apt_repository: 
      repo: 'deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_lsb.codename }} main' 
    become: yes
  - name: Install packages
    apt:
      pkg:
      - docker.io
      - git
      - packer
      - qemu-system-x86
    become: yes
  - name: Add "{{ ansible_user }}" to group docker
    user:
      name: "{{ ansible_user }}"
      groups: docker
      append: yes
    become: yes 
  - name: Add "{{ ansible_user }}" to group kvm
    user:
      name: "{{ ansible_user }}"
      groups: kvm
      append: yes
    become: yes 
  # - name: Restart docker
  #   service:
  #     name: docker
  #     state: restarted
  #   become: yes
  - name: Install microk8s
    community.general.snap:
      name: microk8s
      classic: yes
    become: yes
  - name: Add "{{ ansible_user }}" to microk8s group
    user:
      name: "{{ ansible_user }}"
      groups: microk8s
      append: yes
    become: yes
  - name: Access .kube caching directory
    file:
      path: ~/.kube
      state: directory
      owner: "{{ ansible_user }}"
  - name: Enable microk8s addons
    command: microk8s enable dns ingress registry
  - name: Create alias for kubectl
    lineinfile:
      path:  ~/.bash_aliases
      line: alias kubectl='microk8s kubectl'
      create: yes
      