apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/os: win2k19
  name: vm1
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: vm1
    spec:
      domain:
        cpu:
          cores: 4
        devices:
          disks:
          - name: windows-server
            disk:
              bus: virtio
          - name: cloudinitdisk
            cdrom:
              bus: sata
        machine:
          type: q35
        resources:
          requests:
            memory: 4096M
      volumes:
      - name: windows-server
        containerDisk:
          # image: localhost:5000/windows20h2:latest
          image: windows20h2:local
          # image: kubevirt/cirros-container-disk-demo
      - name: cloudinitdisk
        cloudInitConfigDrive:
          userData: |
            #cloud-config
            write_files:
            - encoding: b64
              content: |
                ewogICJob3N0cyI6IFsidGNwOi8vMC4wLjAuMDoyMzc1IiwgIm5waXBlOi8vIl0sCiAgImluc2Vj
                dXJlLXJlZ2lzdHJpZXMiOiBbXSwKICAibXR1IjogMTQ1MAp9
              path: C:\ProgramData\Docker\config\daemon.json
              permissions: '0644'
            runcmd:
            - 'powershell "Restart-Service docker"'