apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/os: win2k19
  name: vm1
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: vm1
    spec:
      domain:
        cpu:
          cores: 4
        devices:
          disks:
          - name: windows-server
            disk:
              bus: virtio
        machine:
          type: q35
        resources:
          requests:
            memory: 8192M
      volumes:
      - name: windows-server
        containerDisk:
          image: localhost:5000/windows20h2:latest
          # image: kubevirt/cirros-container-disk-demo