apiVersion: apps/v1
kind: Deployment 
metadata:
  name: {{ include "conan-server.fullname" . }}
  labels:
    {{- include "conan-server.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "conan-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "conan-server.labels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "conanio/conan_server:{{ .Values.tag | default "1.28.1" }}"
        volumeMounts:
        - name: config
          mountPath: /root/.conan_server
        - name: storage
          mountPath: /data
        env:
        # For some reason the environment variable is set to a wrong value. Here we overwrite it.
        - name: CONAN_SERVER_PORT
          value: "9300"
        livenessProbe:
          httpGet:
            path: /v2/ping
            port: 9300
      initContainers:
      - name: {{ .Chart.Name }}-setup
        image: busybox:1.28
        command: ['cp', '/config-map/server.conf', '/config']
        volumeMounts:
        - name: config-map
          mountPath: /config-map
        - name: config
          mountPath: /config
      - name: {{ .Chart.Name }}-migrate-data
        image: "conanio/conan_server:{{ .Values.tag | default "1.28.1" }}"
        command: ['python', '-m', 'conans.conan_server', '--migrate']
        volumeMounts:
        - name: config
          mountPath: /root/.conan_server
        - name: storage
          mountPath: /data
        env:
        # For some reason the environment variable is set to a wrong value. Here we overwrite it.
        - name: CONAN_SERVER_PORT
          value: "9300"
      volumes:
      - name: config
        emptyDir: {}
      - name: config-map
        configMap:
          name: {{ include "conan-server.fullname" . }}
      - name: storage
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "conan-server.fullname" .) }}
