apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "conan-server.fullname" $ }}-ingress
  annotations:
    traefik.ingress.kubernetes.io/request-modifier: "ReplacePathRegex: ^/conan/(.*) /$1"
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: {{ .Values.hostName }}
    http:
      paths:
      - path: /conan
        pathType: Prefix
        backend:
          service:
            name: {{ include "conan-server.fullname" . }}
            port: 
              number: 9300
