kind: Service
apiVersion: v1
metadata:
  name: {{ include "conan-server.fullname" . }}
  labels:
    {{- include "conan-server.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "conan-server.selectorLabels" . | nindent 4 }}
  ports:
    - port: 9300
