apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name: {{ include "conan-server.fullname" . }}
  labels:
    {{- include "conan-server.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "conan-server.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "conan-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "conan-server.labels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "conanio/conan_server:{{ .Values.tag | default "1.28.1" }}"
        volumeMounts:
        - name: {{ .Chart.Name }}-config
          mountPath: /root/.conan_server
        - name: {{ .Chart.Name }}-storage
          mountPath: /data
        env:
        # For some reason the environment variable is set to a wrong value. Here we overwrite it.
        - name: CONAN_SERVER_PORT
          value: "9300"
        livenessProbe:
          httpGet:
            path: /v2/ping
            port: 9300
      initContainers:
      - name: {{ .Chart.Name }}-setup
        image: busybox:1.28
        command: ['cp', '/config-map/server.conf', '/config']
        volumeMounts:
        - name: {{ .Chart.Name }}-config-map
          mountPath: /config-map
        - name: {{ .Chart.Name }}-config
          mountPath: /config
      - name: {{ .Chart.Name }}-migrate-data
        image: conanio/conan_server:1.28.1
        command: ['python', '-m', 'conans.conan_server', '--migrate']
        volumeMounts:
        - name: {{ .Chart.Name }}-config
          mountPath: /root/.conan_server
        - name: {{ .Chart.Name }}-storage
          mountPath: /data
        env:
        # For some reason the environment variable is set to a wrong value. Here we overwrite it.
        - name: CONAN_SERVER_PORT
          value: "9300"
      volumes:
      - name: {{ .Chart.Name }}-config
        emptyDir: {}
      - name: {{ .Chart.Name }}-config-map
        configMap:
          name: {{ include "conan-server.fullname" . }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Chart.Name }}-storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100M
